### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arbron** [BradfordC/FoundryVTT-Scene-Defaults#1]
When duplicating a scene or importing a scene from the compendium many existing properties of the scene are overwritten by the default values.

**To Reproduce:**
1. Set default settings with module.
2. Create a scene and change the settings from the defaults.
3. Duplicate the scene in the scene sidebar.

**Expected Behavior:**
Only apply default settings to new scenes created.

**Comment by BradfordC** [comment]
Thanks for the report, I'll look into it.
