### ISSUE TITLE
Not compatible with compendium scenes

### ISSUE THREAD

**Issue by racehd** [BradfordC/FoundryVTT-Scene-Defaults#3]
When I saved scenes into my compendium and later tried to add the scenes from the compendium-- the scene settings had removed the width/length dimensions and the scene image. Upon removing the Scene Defaults module and adding the compendium scene again, it was imported correctly (with background image, proper scene dimensions).  

I think the ideal is for Scene Defaults to not override some of those scene-specific fields from compendium scenes, (or not even be used at all for those?)

**Comment by BradfordC** [comment]
Thanks for the report, I'll check it out.
