### ISSUE TITLE
'Save Scene' button gone on creation

### ISSUE THREAD

**Issue by Squishiest-Grape** [BradfordC/FoundryVTT-Scene-Defaults#5]
When making a new scene in foundry v0.8.6 and Scene Defaults v1.0.2, the save scene button at the bottom of the scene creation window is not longer present.

**Comment by BradfordC** [comment]
I think you might be getting my module mixed up with **Default Scene**, by Hadolonut/assassinduke. Their module has the "Save as Default" option at the bottom of the scene creation window. My module lets you configure the default scene settings through the module settings menu (Configure Settings -> Module Settings -> Scene Defaults -> Edit Scene Defaults).

**Comment by Squishiest-Grape** [comment]
You are correct, I was looking at my module list and 'Default Scene' looks like this:  T_T
![image](https://user-images.githubusercontent.com/48263319/121119722-015e9480-c7d1-11eb-8bdd-2ab51521c637.png)
Apologies
